### ISSUE TITLE
Bierdopje has shutdown, no subs are downloaded

### ISSUE THREAD

**Issue by paulvt** [Sakartu/sicksubs#14]
The subs service of bierdopje has shutdown. See: 
http://www.bierdopje.com/forum/mededelingenforum/topic/16444-Bierdopje-com-stopt-per-direct-met-ondertiteling/1 (English summary at the end of the first post.)
and the output:

```
HTTP Error 403: Bierdopje.com no longer serves subtitles. Please update/disable your application!
HTTP Error 403: Bierdopje.com no longer serves subtitles. Please update/disable your application!
...
```

So I guess we need to look for alternatives?

**Comment by Sakartu** [comment]
I'm afraid so... There are other providers with API access though, as can
be seen in the XBMC subtitle downloader add-on, such as open-subtitles,
podnapisi and others. If I can find the time I'll rewrite sicksubs a bit so
it works again :)

**Comment by Sakartu** [comment]
A good alternative to writing something myself would be to use [periscope]("https://github.com/patrickdessalle/periscope/"), as it already supports most major players (including addic7ed.com, from which many of the bierdopje subs came). I think the coming holidays will give me some time to work something out.

**Comment by Sakartu** [comment]
I have rewritten parts of sicksubs so it can now use periscope in the latest commits. As this is a much more mature framework a lot of code has been removed. The upgrade requires a clean database though, so make sure you remove your old .db file before retrying.

I have added a way of manually adding video files (by providing sicksubs.py with a single argument, which is the path to the video file) so you can reinsert any db entries lost in the process manually. 

Please let me know if you encounter any bugs in the new code :)

**Comment by paulvt** [comment]
Cheers!
I tried running: `./sicksubs.py /path/to/some.mkv', but then I get:

```
Traceback (most recent call last):
  File "./sicksubs.py", line 123, in <module>
    db_path = sys.argv[2]
IndexError: list index out of range
```

Which makes sense, since `sys.argv[2]` doesn't exist if the length of `sys.argv` is 2. I cannot see where in the source it looks at `sys.argv[1]`, except for `sickbeard_run` but that's only called if the lenght is 7.

**Comment by Sakartu** [comment]
Ah, I see I messed up one of the merge conflict resolutions. Should work
now :)

-- Peter

**Comment by Sakartu** [comment]
Ah, I messed up a bunch of other things... Don't know where I was with my head... 

Anyway, tested and it works now, both manually and through the sickbeard call.

Now I just hope that the periscope providers are fast enough for my needs; bierdopje always had subs within a couple of days.

**Comment by paulvt** [comment]
I do not want to bring this ticket up again, but... it seems that now that sicksubs is simplified, it runs periscope on the target filename (i.e. `Series 3x01 - Title.mkv`), but I have the impression that periscope has much more to go on the original file name (i.e. `series.s03e01.group.quality.title.mkv`)?

**Comment by Sakartu** [comment]
It has indeed, but unfortunately Periscope also needs the file to actually
have content, which is impossible as the file was renamed by Sickbeard...
If Sickbeard could create symlinks (instead of renaming) that would
probably solve the problem, but I haven't researched this further yet.

-- Peter

On Tue, Jan 14, 2014 at 12:32 PM, Paul van Tilburg <notifications@github.com
