### ISSUE TITLE
Sicksubs no longer respects the APPEND_LANG setting

### ISSUE THREAD

**Issue by paulvt** [Sakartu/sicksubs#15]
I have it set to `True` but I think that in the rework support for it might have been accidentally dropped?

**Comment by paulvt** [comment]
Uhm, can it be that sicksubs renames my mkvs to ".en.mkv" en still stores subs as ".srt" with `APPEND_LANG` set to `true` instead of naming the subs ".en.srt"?

**Comment by Sakartu** [comment]
You are correct, I messed up the code. Maybe I should actually test before pushing to master... Anyway, it should be fixed now.
