### ISSUE TITLE
Ignores periscope config?

### ISSUE THREAD

**Issue by paulvt** [Sakartu/sicksubs#16]
Since the switch to periscope, I frequently receive e-mails from cron (running sicksubs); for example:

```
ERROR:periscope.plugins.LegendasTV:LegendasTV requires a personnal username/password. Set one up in your ~/.config/periscope/config file
pt
```

Besides that superious "pt\n" being weird, I'm sure I've configured periscope to disable the LegendasTV plugin.  Also when I run periscope manually, it does not give this error. Can it be that periscope is called in such a way that it bypasses the configuration?

**Comment by Sakartu** [comment]
Hey,

I use the following line in the periscope configuration file to disable LegendasTV, in the [DEFAULT] category:

plugins = OpenSubtitles,Subtitulos,Podnapisi,TheSubDB,SubsWiki,SubDivX

I put the line in the ~/.config/periscope/config file for the sickbeard user.

This is part of a bigger problem though: I still get other warnings in my mail from periscope such as when a subtitle page doesn't exist for subtitulos.es (404 message). The problem with ignoring all messages periscope generates (for instance by redirecting stdout/stderr) is that you don't see any configuration errors anymore either...

If you still have problems let me know.

**Comment by Sakartu** [comment]
In related news, I looked into the "pt" printing; it appears to be a problem on [this line ](https://github.com/patrickdessalle/periscope/blob/master/periscope/plugins/TheSubDB.py#L68) in periscope's TheSubDB plugin. In the end I just removed all the plugins except for OpenSubtitles and Podnapisi, since those two account for 99% of all my subtitle downloads.

**Comment by paulvt** [comment]
I will try that, but I already had a periscope config that disabled LegendasTV, so I am/was confused why sicksubs still gave errors about it.

**Comment by Sakartu** [comment]
I seem to have found the problem; periscope was called with a statically defined cache directory, wheras the commandline client uses a directory based on [XDG](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) (or ~/.config/periscope if there is no XDG available). I have changed the call to periscope to more closely resemble the commandline call.

Could you try it again please?

**Comment by paulvt** [comment]
Will do!

**Comment by paulvt** [comment]
Hmm?

```
No handlers could be found for logger "periscope.plugins.OpenSubtitles"
```

**Comment by Sakartu** [comment]
Apparently periscope requires a lot of setup before you can use the python module. Anyway, I added a basic logging setup in the latest commit, periscope should be allowed to print stuff now. The setup honors the -q for sicksubs if given. For debug purposes, the loglevel can be changed to logging.DEBUG in the beginning of cron_run().

**Comment by paulvt** [comment]
Ok, I've updated my repository.. let's see what it does the coming few days! Thanks for the quick fixes.

**Comment by paulvt** [comment]
The only thing that remains is:

```
ERROR:periscope.plugins.OpenSubtitles:Open subtitles could not be contacted for login
```

But that's probably an Periscope issue.

**Comment by paulvt** [comment]
Been testing and it seems to work fine now; at least the config is respected (with only Podnabsi and OpenSubtitles in there as you suggested).
