### ISSUE TITLE
subtitle file permissions

### ISSUE THREAD

**Issue by thomasmattheussen** [Sakartu/sicksubs#17]
Hi,

I recently tried to install sicksubs on my synology NAS. I have a feeling that sicksubs indeed downloads subtitle files, but the files downloaded have limited permissions (-rw-------   sickbeard users)

Where do I fix this?

**Comment by Sakartu** [comment]
In a later email, it appears to be a permission problem on thomasmattheussen's end.

**Comment by thomasmattheussen** [comment]
It may be on my end, but could you help me to fix it? Why does it save the files under 600 permissions?

**Comment by Sakartu** [comment]
Could you check what your umask is? If you login to your server, just run the umask tool and paste here what it shows. In my case it's 002, which means that files created by the sickbeard user will have either 775 (for directories) or 664 (for files, by removing the +x bit) permissions. 

If in your case, the umask is something like 077, this may be the problem, see also [this link](http://unixhelp.ed.ac.uk/examples/umask.html)

**Comment by thomasmattheussen** [comment]
running umask returns 0022, so I guess that should be OK?

**Comment by Sakartu** [comment]
Yes, with umask 0022 created files should have permissions 644, which is default on most distributions (Ubuntu modifies the umask to 002 sometimes, see /etc/login.defs). Could you try to use periscope yourself, as the sickbeard user, to see if a manual download produces the same results?

**Comment by thomasmattheussen** [comment]
I can't seem to get it working. This is the only output I'm getting. Running this on a file for which I know for certain that sicksubs has downloaded subtitles for it (albeit the wrong permissions)

```
INFO:periscope.periscope:lang-in-name read from config: False
INFO:__main__:**************************************************
INFO:__main__:Downloaded 0 subtitles
INFO:__main__:**************************************************
```

**Comment by Sakartu** [comment]
You may have to delete the srt file as periscope won't overwrite existing subs as far as I know. 

Furthermore, I see that you're not getting any plugins whatsoever; what is the output when you run:

`$ periscope --list-plugins`

**Comment by thomasmattheussen** [comment]
Yeah I had already deleted it, so no luck on that one. Running --list-plugins gives:

All plugins: 
OpenSubtitles
Subtitulos
Podnapisi
TheSubDB
SubsWiki
LegendasTV
SubDivX

**Comment by Sakartu** [comment]
To be honest, I don't know what's going on.... Do you have the latest periscope from github? If not, give it a try with the latest version.
