### ISSUE TITLE
DB not migrated

### ISSUE THREAD

**Issue by paulvt** [Sakartu/sicksubs#26]
Now that episodes are timestamped when added (column `added_on`), episodes can no longer be added to an existing database, as it is not migrated.

**Comment by Sakartu** [comment]
To be honest, I don't really plan on adding db migration code for such a simple, low key project. If you want, you can delete your .db file and then readd some files by hand. You can call sicksubs.py with, as a single argument, the path to the episode. If you want to know the current db entries, use the following shellscript as your sickbeard user (assuming sqlite3 is installed as a package):

``` bash
#!/bin/bash
sqlite3 /home/sickbeard/.sicksubs/sicksubs.db <<<"select * from eps;"
```
