### ISSUE TITLE
periscope.plugins.SubtitleDatabase:Error occured

### ISSUE THREAD

**Issue by cagnulein** [Sakartu/sicksubs#27]
[sickbeard@alarmpi sicksubs]$ ./sicksubs.py
INFO:root:Searching subs for /mnt/HD2/files/Telefilm/Hart of Dixie/Season 04/Hart of Dixie - 4x09 - End of Days
INFO:periscope.periscope:Searching subtitles for /mnt/HD2/files/Telefilm/Hart of Dixie/Season 04/Hart of Dixie - 4x09 - End of Days.mkv with langs ['it']
INFO:periscope.periscope:Searching on OpenSubtitles
INFO:periscope.periscope:Searching on Subtitulos
INFO:periscope.periscope:Searching on Podnapisi
INFO:periscope.periscope:Searching on TheSubDB
INFO:periscope.periscope:Searching on BierDopje
INFO:periscope.plugins.SubtitleDatabase:BierDopje writing 0 items to queue
INFO:periscope.periscope:Searching on SubsWiki
INFO:periscope.plugins.SubtitleDatabase:TheSubDB writing 0 items to queue
INFO:periscope.plugins.SubtitleDatabase:OpenSubtitles writing 0 items to queue
INFO:periscope.plugins.SubtitleDatabase:SubsWiki writing 0 items to queue
ERROR:periscope.plugins.SubtitleDatabase:Error occured
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/periscope/plugins/SubtitleDatabase.py", line 44, in searchInThread
    subs = self.process(filename, langs)
  File "/usr/lib/python2.7/site-packages/periscope/plugins/Subtitulos.py", line 55, in process
    subs = self.query(guessedData['name'], guessedData['season'], guessedData['episode'], guessedData['teams'], langs)
  File "/usr/lib/python2.7/site-packages/periscope/plugins/Subtitulos.py", line 85, in query
    status = statusLI.contents[0].string.strip()
AttributeError: 'NoneType' object has no attribute 'contents'

INFO:periscope.plugins.SubtitleDatabase:Podnapisi writing 0 items to queue
INFO:root:No subs available for any of your eps yet!

**Comment by Sakartu** [comment]
Unfortunately, this is a bug in periscope, not in sicksubs... Also, I'm quite sure you're not using the latest version of periscope as bierdopje is no longer a valid periscope provider and has since been removed. 

Please update your version of periscope and try again!
